import { createFourDigitExtension } from "./helpers";
import type { DirectoryContact, Hospital } from "./types";

/**
 * Entirely invented institutions and contact details for local development.
 * The deliberately non-routable-looking prefixes and reserved `.example`
 * domains must be replaced when a moderated backend is connected.
 */
export const HOSPITALS = [
  {
    id: "ospedale-aurora",
    name: "Ospedale Civico Aurora",
    city: "Borgoluce",
    phonePrefix: "+39 000 0001",
  },
  {
    id: "presidio-vallechiara",
    name: "Presidio Sanitario Vallechiara",
    city: "Vallechiara",
    phonePrefix: "+39 000 0002",
  },
  {
    id: "policlinico-montelago",
    name: "Policlinico Montelago",
    city: "Montelago",
    phonePrefix: "+39 000 0003",
  },
] as const satisfies readonly Hospital[];

export const DEFAULT_HOSPITAL_ID = HOSPITALS[0].id;

export const DIRECTORY_CONTACTS = [
  {
    id: "aurora-accettazione-ricoveri",
    hospitalId: "ospedale-aurora",
    name: "Accettazione ricoveri",
    kind: "servizio",
    type: "fisso",
    value: createFourDigitExtension("1101"),
    searchTerms: ["ricovero", "ammissione"],
  },
  {
    id: "aurora-anestesia-rianimazione",
    hospitalId: "ospedale-aurora",
    name: "Anestesia e rianimazione",
    kind: "reparto",
    type: "fisso",
    value: createFourDigitExtension("1210"),
  },
  {
    id: "aurora-cardiologia",
    hospitalId: "ospedale-aurora",
    name: "Cardiologia",
    kind: "reparto",
    type: "fisso",
    value: createFourDigitExtension("1302"),
  },
  {
    id: "aurora-endoscopia",
    hospitalId: "ospedale-aurora",
    name: "Endoscopia digestiva",
    kind: "servizio",
    type: "fisso",
    value: createFourDigitExtension("1414"),
  },
  {
    id: "aurora-guardia-anestesiologica",
    hospitalId: "ospedale-aurora",
    name: "Guardia anestesiologica",
    kind: "ruolo",
    type: "cicalino",
    value: "701",
    searchTerms: ["anestesista", "reperibile"],
  },
  {
    id: "aurora-pronto-soccorso",
    hospitalId: "ospedale-aurora",
    name: "Pronto soccorso",
    kind: "reparto",
    type: "fisso",
    value: createFourDigitExtension("1500"),
    searchTerms: ["emergenza", "urgenza"],
  },
  {
    id: "aurora-radiologia",
    hospitalId: "ospedale-aurora",
    name: "Radiologia",
    kind: "servizio",
    type: "fisso",
    value: createFourDigitExtension("1608"),
  },
  {
    id: "aurora-urp",
    hospitalId: "ospedale-aurora",
    name: "Ufficio relazioni con il pubblico",
    kind: "servizio",
    type: "email",
    value: "urp@aurora.example",
    searchTerms: ["urp", "informazioni"],
  },
  {
    id: "vallechiara-ambulatorio-chirurgico",
    hospitalId: "presidio-vallechiara",
    name: "Ambulatorio chirurgico",
    kind: "servizio",
    type: "fisso",
    value: createFourDigitExtension("2104"),
  },
  {
    id: "vallechiara-cardiologia",
    hospitalId: "presidio-vallechiara",
    name: "Cardiologia",
    kind: "reparto",
    type: "fisso",
    value: createFourDigitExtension("2206"),
  },
  {
    id: "vallechiara-coordinatore-presidio",
    hospitalId: "presidio-vallechiara",
    name: "Coordinatore di presidio",
    kind: "ruolo",
    type: "cicalino",
    value: "42",
    searchTerms: ["coordinamento", "responsabile"],
  },
  {
    id: "vallechiara-dialisi",
    hospitalId: "presidio-vallechiara",
    name: "Dialisi",
    kind: "reparto",
    type: "fisso",
    value: createFourDigitExtension("2312"),
  },
  {
    id: "vallechiara-laboratorio-analisi",
    hospitalId: "presidio-vallechiara",
    name: "Laboratorio analisi",
    kind: "servizio",
    type: "fisso",
    value: createFourDigitExtension("2409"),
  },
  {
    id: "vallechiara-medicina-interna",
    hospitalId: "presidio-vallechiara",
    name: "Medicina interna",
    kind: "reparto",
    type: "fisso",
    value: createFourDigitExtension("2510"),
  },
  {
    id: "vallechiara-pronto-soccorso",
    hospitalId: "presidio-vallechiara",
    name: "Pronto soccorso",
    kind: "reparto",
    type: "fisso",
    value: createFourDigitExtension("2600"),
    searchTerms: ["emergenza", "urgenza"],
  },
  {
    id: "vallechiara-segreteria-sanitaria",
    hospitalId: "presidio-vallechiara",
    name: "Segreteria sanitaria",
    kind: "servizio",
    type: "email",
    value: "segreteria@vallechiara.example",
  },
  {
    id: "montelago-blocco-operatorio",
    hospitalId: "policlinico-montelago",
    name: "Blocco operatorio",
    kind: "servizio",
    type: "fisso",
    value: createFourDigitExtension("3108"),
    searchTerms: ["sale operatorie", "chirurgia"],
  },
  {
    id: "montelago-cardiologia",
    hospitalId: "policlinico-montelago",
    name: "Cardiologia",
    kind: "reparto",
    type: "fisso",
    value: createFourDigitExtension("3205"),
  },
  {
    id: "montelago-emergenze-interne",
    hospitalId: "policlinico-montelago",
    name: "Emergenze interne",
    kind: "ruolo",
    type: "cicalino",
    value: "911",
    searchTerms: ["emergenza", "team urgenze"],
  },
  {
    id: "montelago-farmacia-ospedaliera",
    hospitalId: "policlinico-montelago",
    name: "Farmacia ospedaliera",
    kind: "servizio",
    type: "fisso",
    value: createFourDigitExtension("3311"),
  },
  {
    id: "montelago-neonatologia",
    hospitalId: "policlinico-montelago",
    name: "Neonatologia",
    kind: "reparto",
    type: "fisso",
    value: createFourDigitExtension("3407"),
  },
  {
    id: "montelago-ostetricia-ginecologia",
    hospitalId: "policlinico-montelago",
    name: "Ostetricia e ginecologia",
    kind: "reparto",
    type: "fisso",
    value: createFourDigitExtension("3502"),
  },
  {
    id: "montelago-terapia-intensiva",
    hospitalId: "policlinico-montelago",
    name: "Terapia intensiva",
    kind: "reparto",
    type: "fisso",
    value: createFourDigitExtension("3606"),
    searchTerms: ["rianimazione", "intensiva"],
  },
  {
    id: "montelago-cartelle-cliniche",
    hospitalId: "policlinico-montelago",
    name: "Ufficio cartelle cliniche",
    kind: "servizio",
    type: "email",
    value: "cartelle@montelago.example",
  },
] as const satisfies readonly DirectoryContact[];
